# Authenticate to ubus
POST http://172.20.20.20/cgi-bin/luci/rpc/auth
{
    "id": 3,
    "method": "login",
    "params": ["root", "test"]
}

# Get network info
GET http://172.20.20.20/cgi-bin/luci/rpc/uci?auth=:token
{
    "method": "get_all",
    "params": ["network"]
}

# Get conntrack
GET http://172.20.20.20/cgi-bin/luci/rpc/sys?auth=:token
{
    "method": "net.conntrack"
}

# Get interface info
GET http://172.20.20.20/cgi-bin/luci/rpc/sys?auth=:token
{
    "method": "net.deviceinfo"
}

# Get the password for an user
GET http://172.20.20.20/cgi-bin/luci/rpc/sys?auth=:token
{
    "method": "user.getpasswd",
    "params": ["root"]
}

# Get the route
GET http://172.20.20.20/cgi-bin/luci/rpc/ip?auth=:token
{
    "method": "routes",
    "params": []
}

# Get list of installed packages
GET http://172.20.20.20/cgi-bin/luci/rpc/ipkg?auth=:token
{
    "method": "status",
    "params": ["vim"]
}


# Run a command
GET http://172.20.20.20/cgi-bin/luci/rpc/sys?auth=:token
{
    "method": "process.exec",
    "params": ["echo hello"]
}


# Auth to openwisp
POST https://172.20.20.10/api/v1/user/token/
:auth = 221d623b4806c9d86917b366f2f3ccfa9562e011
Content-Type: application/json
{
    "username": "admin",
    "password": "admin"
}

# Run a command
:device-id = 5fb06af2-3ada-41b6-bb13-52d46ef3a9ee
POST https://172.20.20.10/api/v1/controller/device/:device-id/command
Content-Type: application/json
{
    "input": {"command": "iptables -L"},
    "type": "custom"
}

# Get list of commands executed
GET https://172.20.20.10/api/v1/controller/device/:device-id/command/
Authorization: Bearer :auth
